# Generated by Django 3.2.4 on 2021-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210706_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_image',
            field=models.ImageField(default='default.jpg', upload_to='review/static/upload/cast'),
        ),
        migrations.AlterField(
            model_name='review',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='review/static/upload/poster'),
        ),
    ]
